module.exports = [
  {
    id: 1,
    icon: 'laptop',
    name: '主页',
    router: '/dashboard',
  },
  {
    id: 2,
    bpid: 1,
    name: '微信用户',
    icon: 'message',
    router: '/wxuser',
  },
  {
    id: 3,
    bpid: 1,
    name: '订单',
    icon: 'tags-o',
    router: '/order',
  }, {
    id: 4,
    bpid: 1,
    name: '类型管理',
    icon: 'setting',
  },{
    id: 41,
    bpid: 4,
    mpid: 4,
    name: '目的地国家管理',
    icon: 'flag',
    router: '/destination',
  },{
    id: 411,
    bpid:41,
    mpid:-1,
    name:'省份',
    icon:'flag',
    router: '/province',
  },{
    id: 412,
    bpid:411,
    mpid:-1,
    name:'市级',
    icon:'flag',
    router: '/city',
  },{
    id: 413,
    bpid:412,
    mpid:-1,
    name:'县区',
    icon:'flag',
    router: '/county',
  },{
    id: 42,
    bpid: 4,
    mpid: 4,
    name: '包裹类型管理',
    icon: 'gift',
    router: '/parceltype',
  },{
    id: 43,
    bpid: 4,
    mpid: 4,
    name: '产品类型管理',
    icon: 'filter',
    router: '/product',
  },{
    id: 44,
    bpid: 4,
    mpid: 4,
    name: '运费',
    icon: 'pay-circle-o',
    router: '/freight',
  },{
    id: 5,
    bpid: 1,
    name: '补价管理',
    icon: 'api',
    router: '/boot',
  }, {
    id: 52,
    bpid: 5,
    mpid: -1,
    name: '补价详情',
    router: '/bootdetail',
  }, {
    id: 6,
    bpid: 1,
    name: '推广管理',
    icon: 'global',
    router: '/qr',
  }, {
    id: 61,
    bpid: 6,
    mpid: -1,
    name: '二维码图片',
    router: '/qrdetail',
  },
]
